// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY;

export const isSupabaseConfigured =
  typeof SUPABASE_URL === 'string' &&
  SUPABASE_URL.length > 0 &&
  typeof SUPABASE_PUBLISHABLE_KEY === 'string' &&
  SUPABASE_PUBLISHABLE_KEY.length > 0;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const missingSupabaseConfigError = () =>
  new Error(
    'Supabase is not configured. Add VITE_SUPABASE_URL and one of VITE_SUPABASE_PUBLISHABLE_KEY, VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY, or VITE_SUPABASE_ANON_KEY to .env.'
  );

const fallbackClient = {
  auth: {
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => undefined } } }),
    getSession: async () => ({ data: { session: null }, error: missingSupabaseConfigError() }),
  },
} as unknown as SupabaseClient<Database>;

export const supabase = isSupabaseConfigured
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : fallbackClient;